node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/fadi-mb/sample-spring-microservices.git', credentialsId: 'fadi-mb', branch: 'master'
        }

        stage('Build') {
            bat 'call mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('gateway-service') {
                def app = docker.build "localhost:5000/gateway-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            bat 'docker stop gateway'
            bat 'docker rm gateway' 
            docker.image("localhost:5000/gateway-service:${env.version}").run('-p 1111:1111 -h gateway --name gateway --link discovery --link account --link customer')
        }
     

    }

}